version: '3.8'

services:
  api-gateway:
    build: .
    container_name: universal-identity-gateway
    ports:
      - "8000:8000"
    restart: unless-stopped
    # Environment variables hum yahan pass kar sakte hain
    environment:
      - ENVIRONMENT=production